# QA Environment Configuration
BASE_URL=https://fakerestapi.azurewebsites.net
ENV=qa
USERNAME=qa_user
PASSWORD=qa_password
API_KEY=qa_api_key

// Authors API Configuration
AUTHORS_ENDPOINT=/api/v1/Authors

// Books API Configuration
BOOKS_ENDPOINT=/api/v1/Books
